version: '3.8'
services:
  flask-app:
    build: ./flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=1

  react-app:
    build: ./hello-world-react
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_FLASK_API=http://flask-app:5000
    depends_on:
      - flask-app